### ISSUE TITLE
(Proposal) Unified Namespaces

### ISSUE THREAD

**Issue by AdamSpeight2008** [DotNetAnalyzers/Proposals#32]
The DotNerAnalyzer repos should have a unified approach towards the namespaces they declare,
I propose the following format `namespace Global.DotNetAnalysers.{RepoName}`

examples

```
namespace Global.DotNetAnalyzers
{
 namespace RoslynExts {}
 namespace StyleCopAnalyzers { }
 namespace AsyncUsageAnalysers {}
 namespace VarUsageAnalyzer {}
 namespace DefaultValueDiagnostic {}
}
```

**Comment by sharwell** [comment]
Unfortunately this proposal isn't compatible with the overriding goal of allowing contributors to set their own policies regarding development and distribution of their analyzers.

On the other hand, since users generally aren't interacting directly with the analyzers as an API, the organization of namespaces is unlikely to impact users.

**Comment by sharwell** [comment]
For more information, see the [Guidelines](https://github.com/DotNetAnalyzers/Proposals#guidelines) section of the readme for this repository.
