### ISSUE TITLE
String.Format Diagnostics

### ISSUE THREAD

**Issue by AdamSpeight2008** [DotNetAnalyzers/Proposals#6]
I'm in the process of updating String.Format Diagnostic (SFD) to VS2015.
At moment it causes the compiler / build system to crash. :boom:

**[String.Format Diagnostic](https://stringformatdiagnostic.codeplex.com/)**

Provides pre-compile time diagnostic for format strings and the Arg Holes.

**Arg Hole layout:**  `{ Argument Index , Alignment : Formatting }`
- Argument Index (Required)
- Alignment (Optional)
- Formatting (Optional)

**Diagnostics**
- Are the Argument Indices within range?
- Is the Argument Index less than the in-built limit of 1000000 (Defined inside .net framework)
- Is the Alignment less than the in-built limit of 1000000 (Defined inside .net framework)
- Unexpected Characters
- Unexpectedly reached end of text
- Is the Format Argument valid for the type?
- Unused Parameter Arguments

**Code-Fixes**

There currently isn't any code-fixes provided for these diagnostics.

**Comment by sharwell** [comment]
Hi Adam,

Are you interested in migrating the repository from CodePlex to this organization here on GitHub? You are certainly not required to do so; however, since a repository for this diagnostic already exists, I would encourage users to use the issue tracker and/or pull request mechanism for that repository rather than use the Proposals issue tracker. The main goal of this issue tracker is allowing people to write their ideas down before they even get started working on an analyzer.

Let me know what you'd like to do. :smile: 

Sam

**Comment by AdamSpeight2008** [comment]
Hi Sam,

SFD's repo is staying on codeplex has it has versions on there that support older versions of Visual Studio. _Also I find the syntax for comments used there easier to use than github_ I'm just making people / developers aware that the project exists, as it seem that this repo (yours) is being promoted as a central repository for roslyn-based diagnostics. :smile: It also demonstrates that diagnostics are being implement VB.net, not just C#.:fist:
 -Adam

**Comment by sharwell** [comment]
Hi Adam,

The other option is you can mirror your repository here on GitHub. This would involve the following:
1. Create a repository in this organization which will correspond to your CodePlex repository (I can do this)
2. Disable the issue tracker and wiki for the project, since the source of truth is actually CodePlex
3. Set the description and URL at the top of the repository to indicate that it is a mirror of a CodePlex repository
4. Establish a way to update the GitHub mirror when changes are made to the CodePlex repository. [Github has a help file about this topic](https://help.github.com/articles/about-github-mirrors/), but at the current time it doesn't appear CodePlex supports the necessary actions to automate this so it basically means you'll need to push changes to Github manually after you push changes to CodePlex.

Let me know if you'd like to start mirroring your project here and I can start the process.

**Comment by AdamSpeight2008** [comment]
Sam,
That be cool, I've have to figure out away to automate the push to both.
-Adam

**Comment by sharwell** [comment]
This proposal now has an implementation repository. Please use the issue tracker and/or pull request mechanism associated with the repository for continued discussions regarding the implementation.

https://github.com/DotNetAnalyzers/StringFormatDiagnostic (currently a mirror of a CodePlex repository; see the mirror for a link to the home repository)

**Comment by AdamSpeight2008** [comment]
I've finally figured it out how to mirror the codeplex repo here on github 
Clone -> Mirror -> Delete

**Comment by sharwell** [comment]
@AdamSpeight2008 I didn't follow that

**Comment by AdamSpeight2008** [comment]
I figured out how mirror the repo on Codeplex over to Github (DotNetAnalyser/StringFormatDiagnostic)
